Our-Leaders/our-leaders-admin

src/assets/img/add.svg, src/assets/styles/style.scss, src/components/Navigation.vue, src/components/SideNavigation.vue, src/components/index.js, src/main.js, src/services/services.js, src/store/authStore.js, src/store/userStore.js, src/views/public/Home.vue, tailwind.config.js
=> #12747557 Side nav

src/components/Modals/ModalManager.vue, src/components/Modals/NewPoliticalPartyModal.vue, src/components/SideNavigation.vue, src/services/politicalPartyServices.js, src/vee-validate.js
=> Add modal for adding new political party

package-lock.json, package.json, src/components/AdminDetails.vue, src/components/CountrySelector.vue, src/components/SideNavigation.vue, src/components/Tabs.vue, src/components/index.js, src/filters/index.js, src/router/index.js, src/services/adminServices.js, src/services/factory.js, src/store/adminStore.js, src/store/index.js, src/views/index.js, src/views/public/Admin.vue, src/views/public/Leaders.vue
=> #12771221 View admin list

package-lock.json, package.json, src/assets/img/chevron-left.svg, src/assets/styles/style.scss, src/components/AdminDetails.vue, src/components/Politician.vue, src/components/TextEditor.vue, src/components/index.js, src/components/politicianDetails/AccomplishmentsViews/QuarterView.vue, src/components/politicianDetails/AccomplishmentsViews/YearView.vue, src/components/politicianDetails/PoliticianAccomplishments.vue, src/components/politicianDetails/PoliticianBackground.vue, src/components/politicianDetails/PoliticianManifesto.vue, src/filters/index.js, src/font-awesome.js, src/main.js, src/router/index.js, src/store/politicianStore.js, src/views/index.js, src/views/public/LeaderDetails.vue, src/views/public/Leaders.vue
=> #12772388 Politician details

src/components/Modals/EditPoliticianManifestoModal.vue, src/components/Modals/ModalManager.vue, src/components/Modals/NewPoliticalPartyModal.vue, src/components/SideNavigation.vue, src/components/TextEditor.vue, src/components/politicianDetails/PoliticianManifesto.vue, src/services/politicianServices.js, src/store/index.js, src/store/modalStore.js
=> #12775716 Edit politician manifesto

src/components/Politicalparty.vue, src/components/partyDetails/PartyBackground.vue, src/components/partyDetails/PartyIdeology.vue, src/router/index.js, src/store/politicalPartyStore.js, src/views/index.js, src/views/public/Parties.vue, src/views/public/PartyDetails.vue
=> #12777260 | View political party detail

package-lock.json, src/components/Alert.vue, src/components/TextEditor.vue, src/store/index.js, src/store/notificationStore.js, src/store/pagesStore.js, src/views/public/WebPages.vue
=> #12790781 Admin view and edit contact details

package-lock.json, package.json, src/assets/json/permissions.json, src/components/Modals/JobModal.vue, src/components/Modals/ModalManager.vue, src/components/Modals/NewAdminModal.vue, src/components/Modals/NewPoliticianModal.vue, src/components/Politician.vue, src/components/SideNavigation.vue, src/services/adminServices.js, src/vee-validate.js, src/views/public/Admin.vue, src/views/public/LeaderDetails.vue
=> #12817264 | Super admin can add admin

package-lock.json, package.json, src/components/politicianDetails/PoliticianFeeds.vue, src/router/index.js, src/services/factory.js, src/services/feedServices.js, src/views/public/LeaderDetails.vue
=> #12822995 | Admin can view politician updated

package-lock.json, src/assets/img/image-icon.svg, src/components/NewEditAccomplishment.vue, src/components/index.js, src/services/politicianServices.js, src/store/politicianStore.js, src/views/public/LeaderDetails.vue
=> #12825730 | Add new accomplishment

src/components/Dropdown/Dropdown.vue, src/components/Dropdown/DropdownDivider.vue, src/components/Dropdown/DropdownItem.vue, src/components/Modals/EditProfileModal.vue, src/components/Modals/ModalManager.vue, src/components/Navigation.vue, src/components/SideNavigation.vue, src/router/index.js, src/services/factory.js, src/services/services.js, src/services/userServices.js, src/store/adminStore.js, src/store/authStore.js, src/store/defaultState.js, src/store/index.js, src/store/jobStore.js, src/store/modalStore.js, src/store/pagesStore.js, src/store/politicalPartyStore.js, src/store/politicianStore.js, src/store/statisticsStore.js, src/store/userStore.js, src/views/index.js, src/views/public/Profile.vue
=> #12806299 | Admin can edit their information

src/components/AdminDetails.vue, src/components/Modals/NewAdminModal.vue, src/services/adminServices.js, src/store/adminStore.js, src/views/public/Admin.vue
=> #12840567 | Super Admin can edit admin

src/assets/styles/style.scss, src/components/AdminDetails.vue, src/services/adminServices.js, src/store/adminStore.js
- Adds the feature to block and unblock admins.
=> Feature: Block & Unblock Admnin

package-lock.json, package.json, src/assets/img/add-primary.svg, src/assets/json/permissions.json, src/components/Modals/EditPoliticianBackgroundModal.vue, src/components/Modals/ModalManager.vue, src/components/Navigation.vue, src/components/NewEditAccomplishment.vue, src/components/SideNavigation.vue, src/components/politicianDetails/PoliticianBackground.vue, src/services/politicianServices.js, src/services/services.js, src/store/userStore.js
This displays the modal for editing background.
* It creates or updates existing educational, political or professional background
* It shows an empty field section if there's no background. Validates required fields only if section has started being filled.
* It has a button to add rows which is disabled if there's an empty section above it.
=> Add politician background

package-lock.json, package.json, src/assets/json/countrylist.json, src/components/Modals/EditPoliticalPartyIdeologyModal.vue, src/components/Modals/EditPoliticianBackgroundModal.vue, src/components/Modals/EditPoliticianManifestoModal.vue, src/components/Modals/NewPoliticalPartyModal.vue, src/components/Modals/NewPoliticianModal.vue, src/components/politicianDetails/PoliticianBackground.vue, src/main.js, src/store/defaultState.js, src/store/politicalPartyStore.js, src/store/politicianStore.js, src/views/public/Leaders.vue, src/views/public/Parties.vue
=> Implement pagination for politician and parties

src/components/Modals/ActionModal.vue, src/components/Modals/DeletePoliticianAccomplishmentModal.vue, src/components/Modals/EditPoliticianAccomplishmentModal.vue, src/components/Modals/ModalManager.vue, src/components/NewEditAccomplishment.vue, src/components/politicianDetails/AccomplishmentsViews/QuarterView.vue, src/components/politicianDetails/AccomplishmentsViews/YearView.vue, src/components/politicianDetails/PoliticianAccomplishments.vue, src/helpers/stringUtil.js, src/services/politicianServices.js
This PR adds the edit and delete functionalities for accomplishment
=> Edit and delete accomplishments

package-lock.json, src/assets/styles/style.scss, src/components/SideNavigation.vue, src/store/politicalPartyStore.js, src/store/politicianStore.js, src/views/public/Leaders.vue, src/views/public/Parties.vue
=> Party and politician search

package-lock.json, package.json, src/components/AdminDetails.vue, src/components/CareerComponent.vue, src/components/Modals/EditPoliticalPartyIdeologyModal.vue, src/components/Modals/EditPoliticianBackgroundModal.vue, src/components/Modals/EditPoliticianManifestoModal.vue, src/components/Modals/EditProfileModal.vue, src/components/Modals/JobModal.vue, src/components/Modals/NewAdminModal.vue, src/components/Modals/NewPoliticalPartyModal.vue, src/components/Modals/NewPoliticianModal.vue, src/components/Navigation.vue, src/components/NewEditAccomplishment.vue, src/components/politicianDetails/PoliticianBackground.vue, src/main.js, src/services/adminServices.js, src/services/jobServices.js, src/services/politicalPartyServices.js, src/services/politicianServices.js, src/store/index.js, src/store/politicalPartyStore.js, src/store/politicianStore.js, src/views/public/AdminHome.vue, src/views/public/LeaderDetails.vue, src/views/public/PartyDetails.vue, src/views/public/Profile.vue
> - Add country to Political Party creation
> - Fix issues with creating new Political Party
> - Add deletion of Admins
> - Add notifications for success or failures during resource creation and edit
> - Display Admin image on the navigation bar and profile view
> - Remove country from Political background
=> Changes from review

package.json, src/components/ImageCrop.vue, src/components/Modals/NewPoliticalPartyModal.vue, src/components/Modals/NewPoliticianModal.vue, src/components/index.js, src/main.js
- Creates a cropping component for images.
- Add cropper to politician profile picture upload.
- Add cropper to political party logo upload.
=> Feature: Image Cropper

src/components/Modals/EditContactModal.vue, src/services/authServices.js
- Remove address and phone number as required
=> Feedback: Contacts Page Admin

src/views/auth/SignIn.vue
=> Feature: Sign In Email to Lowercase

src/services/authServices.js, src/views/auth/SignIn.vue
=> Feature: Reset Password

src/services/politicianServices.js, src/views/public/LeaderDetails.vue
Fix issue with Politician data not refreshing on backend change
=> Fix leader details caching issue

src/views/public/Admin.vue
=> Add indication an admin has been deleted

src/components/AdminDetails.vue, src/components/SideNavigation.vue, src/helpers/stringUtil.js, src/router/index.js, src/services/adminServices.js, src/services/userServices.js, src/views/index.js, src/views/public/Archive.vue
- Adds Archive Page.
- Fixes overlapping admin detail side panel on smaller screens.
*NOTE*: The actual page says "Archive", I was just too lazy to take another screenshot.
=> Feature: Archive Page

src/components/Navigation.vue
=> Feature: Mobile Nav

src/views/public/AdminHome.vue, src/views/public/Home.vue
- Makes changes for home page mobile view.
=> Feature: Home Page Mobile View

src/components/CountrySelector.vue, src/components/Politician.vue, src/views/public/Leaders.vue
=> Feature: Leaders Page Mobile View

src/views/public/analytics/Traffic.vue
- Analytics Traffic Mobile View.
=> Feature: Analytics Traffic Mobile View

src/components/Politicalparty.vue, src/views/public/Parties.vue
- Political Party mobile update.
=> Feature: Mobile view for Political Parties Page

src/components/Modals/JobModal.vue, src/views/public/WebPages.vue
=> Feature: Web Pages Mobile View

src/components/Modals/NewPoliticianModal.vue, src/components/Navigation.vue, src/views/public/Archive.vue
=> Feature: Archive Mobile View

src/components/Modals/NewPoliticalPartyModal.vue, src/views/public/PartyDetails.vue
- Mobile view for political party detail and edit modal.
=> Feature: Political Parties Mobile View

src/views/public/analytics/Home.vue
=> Feature: Analytics Mobile

src/assets/styles/style.scss, src/components/Tabs.vue, src/components/politicianDetails/PoliticianBackground.vue, src/helpers/navigatorUtil.js, src/views/public/LeaderDetails.vue, src/views/public/PartyDetails.vue
- Adds leader detail mobile view.
=> Feature: Leader Detail Mobile

src/components/AdminDetails.vue, src/components/Modals/AdminDetailModal.vue, src/components/Modals/ModalManager.vue, src/helpers/navigatorUtil.js, src/views/public/Admin.vue
=> Feature: Admins Mobile View

src/components/Navigation.vue, src/views/public/analytics/Donations.vue, src/views/public/analytics/Signups.vue
- Mobile view update for signups analytics and donation analytics page.
=> Feature: Analystics Signups Donation

src/assets/json/tags.json, src/components/Modals/EditPoliticianBackgroundModal.vue, src/components/NewEditAccomplishment.vue, src/components/politicianDetails/PoliticianAccomplishments.vue, src/views/public/Admin.vue
=> Feature: Nosa Feedback

src/components/Modals/EditPoliticianBackgroundModal.vue
- Makes all background fields optional.
=> Feature: Background Fields Optional
